on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    strategy:
      matrix:
        rust:
          - 1.67.0
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
        name: Install Rust Toolchain
      - run: cargo test
      - run: cargo doc
  test-cachix:
    name: Test w/ Cachix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@12
        with:
          name: mine
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build --impure --max-jobs auto

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: dtolnay/rust-toolchain@stable
        name: Install Rust Toolchain
        with:
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
